const Notifytype = ['PUBLIC','PRIVATEORDERCANCELLEDBYCUSTOMER','PRIVATEORDERCANCELLEDBYVENDOR','PRIVATEORDERCANCELLEDBYTRANSPORTER','PRIVATEORDERRECIEVEDFROMCUSTOMER','PRIVATEORDERACCEPTEDBYTRANSPORTER','PRIVATEORDERACCEPTEDBYVENDOR']

export default Notifytype